config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/login', to: 'home#signin'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post '/contact' => 'contacts#create'
  get '/contact' => 'contacts#new'

  resources :sessions, only: [:create, :destroy]

  namespace :admin do
    root 'home#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
  include ActiveModel::ForbiddenAttributesProtection

  attr_accessor :name, :email, :message
end

app/models/user.rb
class User < ApplicationRecord
  def self.omniauth_auth(omniauth_info)
    data = omniauth_info.info
    user = User.where(email: data[:email]).first
    user
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!

  protected

  def authenticate_user!
    redirect_to root_path unless session[:user_id]
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:id]
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def signin
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.omniauth_auth(request.env['omniauth.auth'])
    if user.nil?
      redirect_to root_path
    else
      session[:user_id] = user.id
      redirect_to admin_root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/views/admin/home/index.html.haml
.content
  %h1 Bienvenido al panel de administracion
  = link_to 'Salir', logout_path

app/views/contacts/new.html.haml
.content
  %h1 Contacto
  = form_for @contact, url: { action: :create },
    html: { class: 'form' } do |form|
    .form-row
      = form.label :name, 'Nombre:', class: 'form-label'
      = form.text_field :name, class: 'form-input'
    .form-row
      = form.label :email, 'Correo electrónico:', class: 'form-label'
      = form.text_field :email, class: 'form-input'
    .form-row
      = form.label :message, 'Tu mensaje:', class: 'form-label'
      = form.text_area :message, class: 'form-input'
    .form-row
      = form.submit 'Enviar mensaje', class: 'button'

app/views/home/index.html.haml
.content
  hola

app/views/home/signin.html.haml
%p.content
  = link_to 'Sign with your google account', '/auth/google_oauth2',
    id: 'sign_in', class: 'button'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title zalapeach blog
    = stylesheet_link_tag 'application', media: :all
  %body
    %section#header
      %figure
        = image_tag 'developer_icon.svg', size: '100x100',
          class: 'header-icon'
      %h1.header-title Juan Carlos Aguilar Rincón
      %p.header-description Ingeniero de software
    %nav.menu
      %ul.menu-content
        %li.menu-element
          = link_to 'Inicio', root_path, class: 'menu-element-link'
        %li.menu-element
          = link_to 'Acerca de mi', '#', class: 'menu-element-link'
        %li.menu-element
          = link_to 'Blog', '#', class: 'menu-element-link'
        %li.menu-element
          = link_to 'Contacto', contact_path, class: 'menu-element-link'
        %li.menu-element
          = link_to 'Curriculum', '#', class: 'menu-element-link'
    = yield
    %footer
      %p.footer-info &copy; Juan Carlos Aguilar Rincón, algunos derechos reservados